## Joins in pandas

common attributes kai base pr dta

## Types

- Inner Join → Only the overlap (3, 4)
- Left Join → Entire left circle (1, 2, 3, 4)
- Right Join → Entire right circle (3, 4, 5, 6)
- Outer Join → Both circles together (1, 2, 3, 4, 5, 6)

In [6]:
import pandas as pd

data = pd.read_excel("test_data.xlsx")

data

   sales_man_id sales_man_name sales_man_city  product_id  manager
0             1          nasir        Karachi         123    jawed
1             2         furqan        lahore          123    jawed
2             3          usman        lahore          345    jawed
3             4          ahmed        karachi         556    najam
4             5         rehman         jhelum         445  shafeeq
5             6          talha      islamabad         556      ali
6             7        huzaifa        karachi         233    najam
7             8         rehman        karachi         778      ali
8             9          akram      islamabad         775  shafeeq

In [16]:
data1 = pd.read_excel("modify.xlsx")

data1

  sales_man_name region  Sales   Amount
0           Asad      A    200   100000
1         rehman      B    220   450000
2        hussain      C    332   125000
3           sana      D    220   652000
4         fatima      E    500   145000
5         kashif      F    321   852000
6   hasan rahman      G    510   125000
7      ab rehman      H    350  3250000
8          ahmed      I    250    86026

In [17]:
pd.merge(data , data1)

,sales_man_id,sales_man_name,sales_man_city,product_id,manager,region,Sales,Amount
0,4,ahmed,karachi,556,najam,I,250,86026
1,5,rehman,jhelum,445,shafeeq,B,220,450000
2,8,rehman,karachi,778,ali,B,220,450000

In [ ]:
# inner join 

pd.merge(data , data1, how = 'inner')

,sales_man_id,sales_man_name,sales_man_city,product_id,manager,region,Sales,Amount
0,4,ahmed,karachi,556,najam,I,250,86026
1,5,rehman,jhelum,445,shafeeq,B,220,450000
2,8,rehman,karachi,778,ali,B,220,450000

In [19]:
pd.merge(data , data1, how = 'outer')

C:\Users\Zohaib Ali\AppData\Roaming\Python\Python314\site-packages\pandas\core\reshape\merge.py:1100: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  result[name] = result._constructor_sliced(

,sales_man_id,sales_man_name,sales_man_city,product_id,manager,region,Sales,Amount
0,NaN,Asad,NaN,NaN,NaN,A,200.0,100000.0
1,NaN,ab rehman,NaN,NaN,NaN,H,350.0,3250000.0
2,4.0,ahmed,karachi,556.0,najam,I,250.0,86026.0
3,9.0,akram,islamabad,775.0,shafeeq,NaN,NaN,NaN
4,NaN,fatima,NaN,NaN,NaN,E,500.0,145000.0
5,2.0,furqan,lahore,123.0,jawed,NaN,NaN,NaN
6,NaN,hasan rahman,NaN,NaN,NaN,G,510.0,125000.0
7,NaN,hussain,NaN,NaN,NaN,C,332.0,125000.0
8,7.0,huzaifa,karachi,233.0,najam,NaN,NaN,NaN
9,NaN,kashif,NaN,NaN,NaN,F,321.0,852000.0
10,1.0,nasir,Karachi,123.0,jawed,NaN,NaN,NaN
11,5.0,rehman,jhelum,445.0,shafeeq,B,220.0,450000.0
12,8.0,rehman,karachi,778.0,ali,B,220.0,450000.0
13,NaN,sana,NaN,NaN,NaN,D,220.0,652000.0
14,6.0,talha,islamabad,556.0,ali,NaN,NaN,NaN
15,3.0,usman,lahore,345.0,jawed,NaN,NaN,NaN

In [21]:
df3 = pd.read_excel("df3.xlsx")
df3

           name region  Sales   Amount
0          Asad      A    200   100000
1        rehman      B    220   450000
2       hussain      C    332   125000
3          sana      D    220   652000
4        fatima      E    500   145000
5        kashif      F    321   852000
6  hasan rahman      G    510   125000
7     ab rehman      H    350  3250000
8         ahmed      I    250    86026

In [24]:
pd.merge(df3 , data1 , left_on = "name" , right_on = "sales_man_name").drop("sales_man_name", axis = 1)

           name region_x  Sales_x  Amount_x region_y  Sales_y  Amount_y
0          Asad        A      200    100000        A      200    100000
1        rehman        B      220    450000        B      220    450000
2       hussain        C      332    125000        C      332    125000
3          sana        D      220    652000        D      220    652000
4        fatima        E      500    145000        E      500    145000
5        kashif        F      321    852000        F      321    852000
6  hasan rahman        G      510    125000        G      510    125000
7     ab rehman        H      350   3250000        H      350   3250000
8         ahmed        I      250     86026        I      250     86026

In [30]:
pd.merge(data , data1, how = "left")

,sales_man_id,sales_man_name,sales_man_city,product_id,manager,region,Sales,Amount
0,1,nasir,Karachi,123,jawed,NaN,NaN,NaN
1,2,furqan,lahore,123,jawed,NaN,NaN,NaN
2,3,usman,lahore,345,jawed,NaN,NaN,NaN
3,4,ahmed,karachi,556,najam,I,250.0,86026.0
4,5,rehman,jhelum,445,shafeeq,B,220.0,450000.0
5,6,talha,islamabad,556,ali,NaN,NaN,NaN
6,7,huzaifa,karachi,233,najam,NaN,NaN,NaN
7,8,rehman,karachi,778,ali,B,220.0,450000.0
8,9,akram,islamabad,775,shafeeq,NaN,NaN,NaN

In [31]:
pd.merge(data1 , data, how = "left")

,sales_man_name,region,Sales,Amount,sales_man_id,sales_man_city,product_id,manager
0,Asad,A,200,100000,NaN,NaN,NaN,NaN
1,rehman,B,220,450000,5.0,jhelum,445.0,shafeeq
2,rehman,B,220,450000,8.0,karachi,778.0,ali
3,hussain,C,332,125000,NaN,NaN,NaN,NaN
4,sana,D,220,652000,NaN,NaN,NaN,NaN
5,fatima,E,500,145000,NaN,NaN,NaN,NaN
6,kashif,F,321,852000,NaN,NaN,NaN,NaN
7,hasan rahman,G,510,125000,NaN,NaN,NaN,NaN
8,ab rehman,H,350,3250000,NaN,NaN,NaN,NaN
9,ahmed,I,250,86026,4.0,karachi,556.0,najam

In [32]:
pd.merge(data , data1, how = "right")

C:\Users\Zohaib Ali\AppData\Roaming\Python\Python314\site-packages\pandas\core\reshape\merge.py:1100: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  result[name] = result._constructor_sliced(

,sales_man_id,sales_man_name,sales_man_city,product_id,manager,region,Sales,Amount
0,NaN,Asad,NaN,NaN,NaN,A,200,100000
1,5.0,rehman,jhelum,445.0,shafeeq,B,220,450000
2,8.0,rehman,karachi,778.0,ali,B,220,450000
3,NaN,hussain,NaN,NaN,NaN,C,332,125000
4,NaN,sana,NaN,NaN,NaN,D,220,652000
5,NaN,fatima,NaN,NaN,NaN,E,500,145000
6,NaN,kashif,NaN,NaN,NaN,F,321,852000
7,NaN,hasan rahman,NaN,NaN,NaN,G,510,125000
8,NaN,ab rehman,NaN,NaN,NaN,H,350,3250000
9,4.0,ahmed,karachi,556.0,najam,I,250,86026