In [80]:
import pandas as pd

data = pd.read_csv("Datasets/car_data.csv")

In [2]:
data.year.value_counts()

year
2015    117
2014     94
2013     94
2016     76
2012     75
       ...
cab       1
t xe      1
EV2       1
r...      1
zest      1
Name: count, Length: 61, dtype: int64

In [3]:
data[data.year == "zest"]

    name company  year     Price kms_driven fuel_type
887   Ta    Tara  zest  3,10,000        NaN       NaN

In [4]:
data.isna().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [5]:
data.kms_driven

0      45,000 kms
1          40 kms
2      22,000 kms
3      28,000 kms
4      36,000 kms
          ...
887           NaN
888    27,000 kms
889    40,000 kms
890        Petrol
891        Petrol
Name: kms_driven, Length: 892, dtype: str

In [25]:
data[data.kms_driven == 'Petrol']

                          name    company  year     Price kms_driven fuel_type
890   Honda Amaze 1.2 E i VTEC      Honda  2014  1,80,000     Petrol       NaN
891  Chevrolet Sail 1.2 LT ABS  Chevrolet  2014  1,60,000     Petrol       NaN

In [32]:
data.kms_driven.replace("Petrol", 0, inplace=True)
data.kms_driven

C:\Users\Zohaib Ali\AppData\Local\Temp\ipykernel_17700\808768526.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data.kms_driven.replace("Petrol", 0, inplace=True)

0      45,000 kms
1          40 kms
2      22,000 kms
3      28,000 kms
4      36,000 kms
          ...
887           NaN
888    27,000 kms
889    40,000 kms
890        Petrol
891        Petrol
Name: kms_driven, Length: 892, dtype: str

In [81]:
d1 = data.kms_driven.str.replace("kms" , ' ').str.replace(",", '')

d1

0      45000
1         40
2      22000
3      28000
4      36000
        ...
887        NaN
888    27000
889    40000
890     Petrol
891     Petrol
Name: kms_driven, Length: 892, dtype: str

In [82]:
d1.replace("NaN", 0)
d1

0      45000
1         40
2      22000
3      28000
4      36000
        ...
887        NaN
888    27000
889    40000
890     Petrol
891     Petrol
Name: kms_driven, Length: 892, dtype: str

In [83]:
data = d1.fillna(0)
data

0      45000
1         40
2      22000
3      28000
4      36000
        ...
887          0
888    27000
889    40000
890     Petrol
891     Petrol
Name: kms_driven, Length: 892, dtype: object

In [74]:
data = data.astype(int)

In [ ]:
data.median()

np.float64(39000.0)

In [77]:
data = data.fillna(data.median())
data

0      45000
1         40
2      22000
3      28000
4      36000
       ...
887        0
888    27000
889    40000
890        0
891        0
Name: kms_driven, Length: 892, dtype: int64