In [4]:
import pandas as pd

data = pd.read_csv("Datasets/car_data.csv")

data.name.isna().sum()

FileNotFoundError: [Errno 2] No such file or directory: 'Datasets/car_data.csv'

## missing values identify by isna aur sum total values btaarha kitni missing

In [ ]:


data.isna().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

## Dropping col / record that has missing values

In [9]:
data.dropna(axis=0)

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,"2,70,000","50,000 kms",Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,"1,10,000","30,000 kms",Diesel
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel

## axis 0 hota hai dropna ka aur axis pai rows delete hongi and axis 1 pai column delete hoga

In [10]:
data.dropna(axis=1)

                                       name    company  year          Price
0      Hyundai Santro Xing XO eRLX Euro III    Hyundai  2007         80,000
1                   Mahindra Jeep CL550 MDI   Mahindra  2006       4,25,000
2                Maruti Suzuki Alto 800 Vxi     Maruti  2018  Ask For Price
3    Hyundai Grand i10 Magna 1.2 Kappa VTVT    Hyundai  2014       3,25,000
4          Ford EcoSport Titanium 1.5L TDCi       Ford  2014       5,75,000
..                                      ...        ...   ...            ...
887                                      Ta       Tara  zest       3,10,000
888                     Tata Zest XM Diesel       Tata  2018       2,60,000
889                      Mahindra Quanto C8   Mahindra  2013       3,90,000
890                Honda Amaze 1.2 E i VTEC      Honda  2014       1,80,000
891               Chevrolet Sail 1.2 LT ABS  Chevrolet  2014       1,60,000

[892 rows x 4 columns]

## Threshold aik number btado us hisaab sai chk krei g 5 col chk kro aik bhi NA hoa to delete and ya 5 records ko check krei g aik bhi missing hoi too rcord urha dega aur aik bhi missing nhi to record / col rkhai g 

## 4 threshold means shuruu kai 4

In [10]:
import pandas as pd

data = pd.read_csv("Datasets/car_data.csv")

data.dropna(axis=0, thresh=6)

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,"2,70,000","50,000 kms",Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,"1,10,000","30,000 kms",Diesel
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel

## 0.70 70 Percent data utha kai dedega 0 for rows and 1 for columns 
## Threshold mai 70 percent columns ajain gai

In [18]:
data.shape[0]*0.70

data.dropna(axis=0, thresh=int(data.shape[1]*0.70))

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN