In [ ]:
import pandas as pd

data = pd.read_csv("Datasets/kAtMSa.csv")

data.head(5)

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [2]:
import pandas as pd 
movies = pd.read_csv("Datasets/movie.csv")

movies

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,80.0,Frank Darabont,Tim Robbins,2343110,28341469.0
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,100.0,Francis Ford Coppola,Marlon Brando,1620367,134966411.0
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,84.0,Christopher Nolan,Christian Bale,2303232,534858444.0
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,90.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,96.0,Sidney Lumet,Henry Fonda,689845,4360000.0
...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,76.0,Blake Edwards,Audrey Hepburn,166544,NaN
996,Giant,1956,G,201 min,"Drama, Western",7.6,84.0,George Stevens,Elizabeth Taylor,34075,NaN
997,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,85.0,Fred Zinnemann,Burt Lancaster,43374,30500000.0
998,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,78.0,Alfred Hitchcock,Tallulah Bankhead,26471,NaN
999,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,93.0,Alfred Hitchcock,Robert Donat,51853,NaN

In [6]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   str
 1   Released_Year  1000 non-null   str
 2   Certificate    899 non-null    str
 3   Runtime        1000 non-null   str
 4   Genre          1000 non-null   str
 5   IMDB_Rating    1000 non-null   float64
 6   Meta_score     843 non-null    float64
 7   Director       1000 non-null   str
 8   Star1          1000 non-null   str
 9   No_of_Votes    1000 non-null   int64
 10  Gross          831 non-null    float64
dtypes: float64(3), int64(1), str(7)
memory usage: 86.1 KB

In [11]:
movies.Released_Year.unique()

<StringArray>
['1994', '1972', '2008', '1974', '1957', '2003', '1993', '2010', '1999',
 '2001', '1966', '2002', '1990', '1980', '1975', '2020', '2019', '2014',
 '1998', '1997', '1995', '1991', '1977', '1962', '1954', '1946', '2011',
 '2006', '2000', '1988', '1985', '1968', '1960', '1942', '1936', '1931',
 '2018', '2017', '2016', '2012', '2009', '2007', '1984', '1981', '1979',
 '1971', '1963', '1964', '1950', '1940', '2013', '2005', '2004', '1992',
 '1987', '1986', '1983', '1976', '1973', '1965', '1959', '1958', '1952',
 '1948', '1944', '1941', '1927', '1921', '2015', '1996', '1989', '1978',
 '1961', '1955', '1953', '1925', '1924', '1982', '1967', '1951', '1949',
 '1939', '1937', '1934', '1928', '1926', '1920', '1970', '1969', '1956',
 '1947', '1945', '1930', '1938', '1935', '1933', '1932', '1922', '1943',
   'PG']
Length: 100, dtype: str

In [13]:
movies.Released_Year.value_counts()

Released_Year
2014    32
2004    31
2009    29
2016    28
2013    28
        ..
1920     1
1930     1
1922     1
1943     1
PG       1
Name: count, Length: 100, dtype: int64

In [33]:
movies.loc[966]

Series_Title                     Apollo 13
Released_Year                         1995
Certificate                              U
Runtime                            140 min
Genre            Adventure, Drama, History
IMDB_Rating                            7.6
Meta_score                            77.0
Director                        Ron Howard
Star1                            Tom Hanks
No_of_Votes                         269197
Gross                          173837933.0
Name: 966, dtype: object

In [19]:
movies.Released_Year.value_counts()

Released_Year
2014    32
2004    31
2009    29
2016    28
2013    28
        ..
1920     1
1930     1
1922     1
1943     1
PG       1
Name: count, Length: 100, dtype: int64

In [36]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   str
 1   Released_Year  1000 non-null   str
 2   Certificate    899 non-null    str
 3   Runtime        1000 non-null   str
 4   Genre          1000 non-null   str
 5   IMDB_Rating    1000 non-null   float64
 6   Meta_score     843 non-null    float64
 7   Director       1000 non-null   str
 8   Star1          1000 non-null   str
 9   No_of_Votes    1000 non-null   int64
 10  Gross          831 non-null    float64
dtypes: float64(3), int64(1), str(7)
memory usage: 86.1 KB

In [39]:
data.tail(5)

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
995,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,76.0,Blake Edwards,Audrey Hepburn,166544,NaN
996,Giant,1956,G,201 min,"Drama, Western",7.6,84.0,George Stevens,Elizabeth Taylor,34075,NaN
997,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,85.0,Fred Zinnemann,Burt Lancaster,43374,30500000.0
998,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,78.0,Alfred Hitchcock,Tallulah Bankhead,26471,NaN
999,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,93.0,Alfred Hitchcock,Robert Donat,51853,NaN

In [43]:
movies.Released_Year.replace("PG", 1995, inplace=True)

C:\Users\Zohaib Ali\AppData\Local\Temp\ipykernel_11820\323181817.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  movies.Released_Year.replace("PG", 1995, inplace=True)

0      1994
1      1972
2      2008
3      1974
4      1957
       ...
995    1961
996    1956
997    1953
998    1944
999    1935
Name: Released_Year, Length: 1000, dtype: str

In [54]:
data = movies.loc[966, "Released_Year"]

int(data)

data

'1995'

In [ ]:
#permanently chnge the data type of released year

movies.Released_Year = movies.Released_Year.astype(int)

In [59]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   str
 1   Released_Year  1000 non-null   int64
 2   Certificate    899 non-null    str
 3   Runtime        1000 non-null   str
 4   Genre          1000 non-null   str
 5   IMDB_Rating    1000 non-null   float64
 6   Meta_score     843 non-null    float64
 7   Director       1000 non-null   str
 8   Star1          1000 non-null   str
 9   No_of_Votes    1000 non-null   int64
 10  Gross          831 non-null    float64
dtypes: float64(3), int64(2), str(6)
memory usage: 86.1 KB

In [61]:
movies.describe()

       Released_Year  IMDB_Rating  Meta_score   No_of_Votes         Gross
count    1000.000000  1000.000000  843.000000  1.000000e+03  8.310000e+02
mean     1991.221000     7.949300   77.971530  2.736929e+05  6.803475e+07
std        23.285669     0.275491   12.376099  3.273727e+05  1.097500e+08
min      1920.000000     7.600000   28.000000  2.508800e+04  1.305000e+03
25%      1976.000000     7.700000   70.000000  5.552625e+04  3.253559e+06
50%      1999.000000     7.900000   79.000000  1.385485e+05  2.353089e+07
75%      2009.000000     8.100000   87.000000  3.741612e+05  8.075089e+07
max      2020.000000     9.300000  100.000000  2.343110e+06  9.366622e+08

In [62]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   str
 1   Released_Year  1000 non-null   int64
 2   Certificate    899 non-null    str
 3   Runtime        1000 non-null   str
 4   Genre          1000 non-null   str
 5   IMDB_Rating    1000 non-null   float64
 6   Meta_score     843 non-null    float64
 7   Director       1000 non-null   str
 8   Star1          1000 non-null   str
 9   No_of_Votes    1000 non-null   int64
 10  Gross          831 non-null    float64
dtypes: float64(3), int64(2), str(6)
memory usage: 86.1 KB

In [65]:
movies.Runtime

0      142 min
1      175 min
2      152 min
3      202 min
4       96 min
        ...
995    115 min
996    201 min
997    118 min
998     97 min
999     86 min
Name: Runtime, Length: 1000, dtype: str

In [5]:
import pandas as pd
movies = pd.read_csv("movie.csv")

0      142 min
1      175 min
2      152 min
3      202 min
4       96 min
        ...
995    115 min
996    201 min
997    118 min
998     97 min
999     86 min
Name: Runtime, Length: 1000, dtype: str

In [6]:
movies.Runtime.replace("min", "")

0      142 min
1      175 min
2      152 min
3      202 min
4       96 min
        ...
995    115 min
996    201 min
997    118 min
998     97 min
999     86 min
Name: Runtime, Length: 1000, dtype: str

In [8]:
movies.Runtime.str.replace("min","").astype(int)

0      142
1      175
2      152
3      202
4       96
      ...
995    115
996    201
997    118
998     97
999     86
Name: Runtime, Length: 1000, dtype: int64

In [ ]:
movies.Runtime = movies.Runtime.str.replace("min","").astype(int)

In [10]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   str
 1   Released_Year  1000 non-null   str
 2   Certificate    899 non-null    str
 3   Runtime        1000 non-null   int64
 4   Genre          1000 non-null   str
 5   IMDB_Rating    1000 non-null   float64
 6   Meta_score     843 non-null    float64
 7   Director       1000 non-null   str
 8   Star1          1000 non-null   str
 9   No_of_Votes    1000 non-null   int64
 10  Gross          831 non-null    float64
dtypes: float64(3), int64(2), str(6)
memory usage: 86.1 KB

In [22]:
# Top 5 Director in terms of Gross

movies.Gross.max()

np.float64(936662225.0)

In [27]:
movies.sort_values(by="Gross", ascending=False).head()[["Director","Gross"]]

          Director        Gross
477    J.J. Abrams  936662225.0
59   Anthony Russo  858373000.0
623  James Cameron  760507625.0
60   Anthony Russo  678815482.0
652  James Cameron  659325379.0

In [34]:
movies.sort_values(by="Gross", ascending=True).tail(5)[["Director","Gross"]]

                   Director  Gross
993  Michelangelo Antonioni    NaN
995           Blake Edwards    NaN
996          George Stevens    NaN
998        Alfred Hitchcock    NaN
999        Alfred Hitchcock    NaN

In [35]:
movies.tail(5)

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
995,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,76.0,Blake Edwards,Audrey Hepburn,166544,NaN
996,Giant,1956,G,201 min,"Drama, Western",7.6,84.0,George Stevens,Elizabeth Taylor,34075,NaN
997,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,85.0,Fred Zinnemann,Burt Lancaster,43374,30500000.0
998,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,78.0,Alfred Hitchcock,Tallulah Bankhead,26471,NaN
999,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,93.0,Alfred Hitchcock,Robert Donat,51853,NaN

In [39]:
movies.Genre.unique()

<StringArray>
[                     'Drama',               'Crime, Drama',
       'Action, Crime, Drama',   'Action, Adventure, Drama',
  'Biography, Drama, History',  'Action, Adventure, Sci-Fi',
             'Drama, Romance',                    'Western',
             'Action, Sci-Fi',    'Biography, Crime, Drama',
 ...
     'Drama, Horror, Mystery',   'Animation, Comedy, Crime',
   'Action, Adventure, Crime', 'Action, Adventure, Mystery',
  'Action, Adventure, Family',     'Action, Crime, Mystery',
                       '1995',  'Animation, Drama, Romance',
        'Drama, War, Western',     'Adventure, Comedy, War']
Length: 203, dtype: str

In [ ]:
dic_gross = movies.sort_values(by="Gross", ascending=False).head(20)[["Director","Gross"]]

              Director        Gross
477        J.J. Abrams  936662225.0
59       Anthony Russo  858373000.0
623      James Cameron  760507625.0
60       Anthony Russo  678815482.0
652      James Cameron  659325379.0
357        Joss Whedon  623279547.0
891          Brad Bird  608581744.0
2    Christopher Nolan  534858444.0
582     Gareth Edwards  532177324.0
63   Christopher Nolan  448139099.0
688   Steven Spielberg  435110554.0
596        Josh Cooley  434038008.0
43        Roger Allers  422783777.0
151        Lee Unkrich  415004880.0
583      Anthony Russo  408084349.0
262   Steven Spielberg  402453882.0
887         James Gunn  389813101.0
226        David Yates  381011219.0
242     Andrew Stanton  380843261.0
5        Peter Jackson  377845905.0

In [43]:
import matplotlib.pyplot as plt

plt.bar(x=dic_gross.Director, height = dic-gross.Gross)

ModuleNotFoundError: No module named 'matplotlib'

In [44]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [45]:
# get all the adventure movies whose imdb rating < 7 ad meta score > 80 


movies

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,80.0,Frank Darabont,Tim Robbins,2343110,28341469.0
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,100.0,Francis Ford Coppola,Marlon Brando,1620367,134966411.0
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,84.0,Christopher Nolan,Christian Bale,2303232,534858444.0
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,90.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,96.0,Sidney Lumet,Henry Fonda,689845,4360000.0
...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,76.0,Blake Edwards,Audrey Hepburn,166544,NaN
996,Giant,1956,G,201 min,"Drama, Western",7.6,84.0,George Stevens,Elizabeth Taylor,34075,NaN
997,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,85.0,Fred Zinnemann,Burt Lancaster,43374,30500000.0
998,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,78.0,Alfred Hitchcock,Tallulah Bankhead,26471,NaN
999,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,93.0,Alfred Hitchcock,Robert Donat,51853,NaN

In [ ]:
movies[(movies.IMDB_Rating < 7) & (movies.Meta_score > 80)]

Empty DataFrame
Columns: [Series_Title, Released_Year, Certificate, Runtime, Genre, IMDB_Rating, Meta_score, Director, Star1, No_of_Votes, Gross]
Index: []

In [49]:
movies[(movies.Genre.str.contains("Action")) & (movies.IMDB_Rating < 8) & (movies.Meta_score > 80)]

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
488,District 9,2009,A,112 min,"Action, Sci-Fi, Thriller",7.9,81.0,Neill Blomkamp,Sharlto Copley,638202,115646235.0
493,Star Trek,2009,UA,127 min,"Action, Adventure, Sci-Fi",7.9,82.0,J.J. Abrams,Chris Pine,577336,257730019.0
496,Letters from Iwo Jima,2006,UA,141 min,"Action, Adventure, Drama",7.9,89.0,Clint Eastwood,Ken Watanabe,154011,13756082.0
507,Ying xiong,2002,PG-13,120 min,"Action, Adventure, History",7.9,85.0,Yimou Zhang,Jet Li,173999,53710019.0
543,The Wild Bunch,1969,A,145 min,"Action, Adventure, Western",7.9,97.0,Sam Peckinpah,William Holden,77401,12064472.0
564,The Adventures of Robin Hood,1938,PG,102 min,"Action, Adventure, Romance",7.9,97.0,Michael Curtiz,William Keighley,47175,3981000.0
573,Dunkirk,2017,UA,106 min,"Action, Drama, History",7.8,94.0,Christopher Nolan,Fionn Whitehead,555092,188373161.0
578,Kubo and the Two Strings,2016,PG,101 min,"Animation, Action, Adventure",7.8,84.0,Travis Knight,Charlize Theron,118035,48023088.0
623,Avatar,2009,UA,162 min,"Action, Adventure, Fantasy",7.8,83.0,James Cameron,Sam Worthington,1118998,760507625.0
627,Hot Fuzz,2007,UA,121 min,"Action, Comedy, Mystery",7.8,81.0,Edgar Wright,Simon Pegg,463466,23637265.0
645,Wo hu cang long,2000,UA,120 min,"Action, Adventure, Fantasy",7.8,94.0,Ang Lee,Yun-Fat Chow,253228,128078872.0
663,The Fugitive,1993,U,130 min,"Action, Crime, Drama",7.8,87.0,Andrew Davis,Harrison Ford,267684,183875760.0
674,Dip huet seung hung,1989,R,111 min,"Action, Crime, Drama",7.8,82.0,John Woo,Yun-Fat Chow,45624,NaN
696,Badlands,1973,PG,94 min,"Action, Crime, Drama",7.8,93.0,Terrence Malick,Martin Sheen,66009,NaN
702,Bonnie and Clyde,1967,A,111 min,"Action, Biography, Crime",7.8,86.0,Arthur Penn,Warren Beatty,102415,NaN
718,Scarface: The Shame of the Nation,1932,PG,93 min,"Action, Crime, Drama",7.8,87.0,Howard Hawks,Richard Rosson,25312,NaN
725,Mission: Impossible - Fallout,2018,UA,147 min,"Action, Adventure, Thriller",7.7,86.0,Christopher McQuarrie,Tom Cruise,291257,220159104.0
744,The Lego Movie,2014,U,100 min,"Animation, Action, Adventure",7.7,83.0,Christopher Miller,Phil Lord,323982,257760692.0
751,Skyfall,2012,UA,143 min,"Action, Adventure, Thriller",7.7,81.0,Sam Mendes,Daniel Craig,630614,304360277.0
850,Enter the Dragon,1973,A,102 min,"Action, Crime, Drama",7.7,83.0,Robert Clouse,Bruce Lee,96561,25000000.0
852,The French Connection,1971,A,104 min,"Action, Crime, Drama",7.7,94.0,William Friedkin,Gene Hackman,110075,15630710.0
853,Dirty Harry,1971,A,102 min,"Action, Crime, Thriller",7.7,90.0,Don Siegel,Clint Eastwood,143292,35900000.0
861,Goldfinger,1964,A,110 min,"Action, Adventure, Thriller",7.7,87.0,Guy Hamilton,Sean Connery,174119,51081062.0
888,Baby Driver,2017,UA,113 min,"Action, Crime, Drama",7.6,86.0,Edgar Wright,Ansel Elgort,439406,107825862.0
893,Sicario,2015,A,121 min,"Action, Crime, Drama",7.6,82.0,Denis Villeneuve,Emily Blunt,371291,46889293.0
896,Hell or High Water,2016,R,102 min,"Action, Crime, Drama",7.6,88.0,David Mackenzie,Chris Pine,204175,26862450.0
918,Eastern Promises,2007,R,100 min,"Action, Crime, Drama",7.6,82.0,David Cronenberg,Naomi Watts,227760,17114882.0
944,Batoru rowaiaru,2000,NaN,114 min,"Action, Adventure, Drama",7.6,81.0,Kinji Fukasaku,Tatsuya Fujiwara,169091,NaN