In [31]:
import pandas as pd 

df = pd.read_csv("laptop.csv")

In [61]:
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.336
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.808
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.64
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.72
1300,1300.0,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.12
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.92
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.32

In [32]:
df.fillna({"Unnamed: 0": df["Unnamed: 0"].mode()[0]}, inplace=True)

df.isna().sum()

C:\Users\Zohaib Ali\AppData\Local\Temp\ipykernel_15816\431081815.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.fillna({"Unnamed: 0": df["Unnamed: 0"].mode()[0]}, inplace=True)

Unnamed: 0           0
Company             30
TypeName            30
Inches              30
ScreenResolution    30
Cpu                 30
Ram                 30
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [36]:
df.fillna({"Company": df.Company.mode()[0]}, inplace=True)

df.isna().sum()

Unnamed: 0           0
Company              0
TypeName             0
Inches              30
ScreenResolution    30
Cpu                 30
Ram                 30
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [34]:
df.fillna({"TypeName": df.TypeName.mode()[0]}, inplace=True)

df.isna().sum()

Unnamed: 0           0
Company              0
TypeName             0
Inches              30
ScreenResolution    30
Cpu                 30
Ram                 30
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [54]:
df["Inches"] = df["Inches"].str.replace('"', "", regex=False)

In [ ]:

df["Inches"] = df["Inches"].replace({"none": None, "?": None})

In [56]:
df["Inches"] = pd.to_numeric(df["Inches"], errors="coerce")

In [60]:
df.fillna({"Inches": df.Inches.mode()[0]}, inplace=True)

df.isna().sum()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1303 non-null   float64
 1   Company           1303 non-null   object
 2   TypeName          1303 non-null   object
 3   Inches            1303 non-null   float64
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   Ram               1273 non-null   object
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight            1273 non-null   object
 11  Price             1273 non-null   object
dtypes: float64(2), object(10)
memory usage: 122.3+ KB

In [63]:
df.fillna({"ScreenResolution": df.ScreenResolution.mode()[0]}, inplace=True)

df.isna().sum()

Unnamed: 0           0
Company              0
TypeName             0
Inches               0
ScreenResolution     0
Cpu                 30
Ram                 30
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [64]:
df.fillna({"Cpu": df.Cpu.mode()[0]}, inplace=True)

df.isna().sum()

Unnamed: 0           0
Company              0
TypeName             0
Inches               0
ScreenResolution     0
Cpu                  0
Ram                 30
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1303 non-null   float64
 1   Company           1303 non-null   object
 2   TypeName          1303 non-null   object
 3   Inches            1303 non-null   float64
 4   ScreenResolution  1303 non-null   object
 5   Cpu               1303 non-null   object
 6   Ram               1273 non-null   object
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight            1273 non-null   object
 11  Price             1273 non-null   object
dtypes: float64(2), object(10)
memory usage: 122.3+ KB

In [66]:
df["Ram"] = df["Ram"].str.replace('"', "", regex=False)
df["Ram"] = df["Ram"].str.replace("GB", "", regex=False)

In [68]:
df["Ram"] = pd.to_numeric(df["Ram"], errors="coerce")
df.fillna({"Ram": df.Ram.mode()[0]}, inplace=True)

df.isna().sum()

Unnamed: 0           0
Company              0
TypeName             0
Inches               0
ScreenResolution     0
Cpu                  0
Ram                  0
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [70]:
df["Memory"] = df["Memory"].replace({"?": None})
df.fillna({"Memory": df.Memory.mode()[0]}, inplace=True)

df.isna().sum()

Unnamed: 0           0
Company              0
TypeName             0
Inches               0
ScreenResolution     0
Cpu                  0
Ram                  0
Memory               0
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [71]:
df.fillna({"Gpu": df.Gpu.mode()[0]}, inplace=True)

df.isna().sum()

Unnamed: 0           0
Company              0
TypeName             0
Inches               0
ScreenResolution     0
Cpu                  0
Ram                  0
Memory               0
Gpu                  0
OpSys               30
Weight              30
Price               30
dtype: int64

In [72]:
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8.0,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8.0,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8.0,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16.0,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.336
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8.0,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.808
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4.0,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.64
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16.0,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.72
1300,1300.0,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2.0,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.12
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6.0,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.92
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4.0,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.32

In [74]:
df["OpSys"] = df["OpSys"].replace({"Mac OS X": "macOS", "Windows 10 S": "Windows 10"})
df.fillna({"OpSys": df.OpSys.mode()[0]}, inplace=True)

df.isna().sum()

Unnamed: 0           0
Company              0
TypeName             0
Inches               0
ScreenResolution     0
Cpu                  0
Ram                  0
Memory               0
Gpu                  0
OpSys                0
Weight              30
Price               30
dtype: int64

In [75]:
df["Weight"] = df["Weight"].str.replace("kg", "", regex=False)
df["Weight"] = df["Weight"].replace({"?": None})

In [77]:
df["Weight"] = pd.to_numeric(df["Weight"], errors="coerce")
df.fillna({"Weight": df.Weight.mode()[0]}, inplace=True)

df.isna().sum()

Unnamed: 0           0
Company              0
TypeName             0
Inches               0
ScreenResolution     0
Cpu                  0
Ram                  0
Memory               0
Gpu                  0
OpSys                0
Weight               0
Price               30
dtype: int64

In [79]:
df["Price"] = df["Price"].replace({"none": None})
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")
df.fillna({"Price": df.Price.mode()[0]}, inplace=True)

df.isna().sum()

Unnamed: 0          0
Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [80]:
df.isnull().sum()

Unnamed: 0          0
Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [81]:
df.shape

(1303, 12)

In [82]:
df.to_csv("C:\Vs Code\SMIT\Day 03\laptop_filled_only.csv", index=False)

<>:1: SyntaxWarning: "\V" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\V"? A raw string is also an option.
<>:1: SyntaxWarning: "\V" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\V"? A raw string is also an option.
C:\Users\Zohaib Ali\AppData\Local\Temp\ipykernel_15816\4012137149.py:1: SyntaxWarning: "\V" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\V"? A raw string is also an option.
  df.to_csv("C:\Vs Code\SMIT\Day 03\laptop_filled_only.csv", index=False)