In [1]:
import pandas as pd

## Transforming data Using a Function or Mapping 

.replace
.apply 
.transform
.map

In [22]:
data = pd.DataFrame([ "cat", "dog", "lion", "elephant", "cat", "bird", "dog", "cat", "bird", "dog", "cat", "bird"],
                     columns = ["Animal"])

data

      Animal
0        cat
1        dog
2       lion
3   elephant
4        cat
5       bird
6        dog
7        cat
8       bird
9        dog
10       cat
11      bird

## Mapping , aik cheez ko aik class ya grp provide krdia

In [24]:
dic = {'cat': 'pet', 'dog': 'pet', 'lion': 'wild', 'elephant': 'wild', 'bird': 'pet'}

In [25]:
data["Type"] = data.Animal.map(dic)

In [26]:
data

      Animal  Type
0        cat   pet
1        dog   pet
2       lion  wild
3   elephant  wild
4        cat   pet
5       bird   pet
6        dog   pet
7        cat   pet
8       bird   pet
9        dog   pet
10       cat   pet
11      bird   pet