# Data Transformation 

## Removing Duplicates

In [1]:
import pandas as pd

data = pd.read_excel("employee.xlsx")

In [ ]:
data.duplicated()

np.int64(0)

In [ ]:
dup_data = pd.read_excel("dup_employee.xlsx")

dup_data.duplicated()

np.int64(6)

In [10]:
dup_data.duplicated(subset=["Age"])

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12     True
13     True
14    False
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
dtype: bool

## Keep last means last wali rkh le ga 

## Keep first means first wali rkh le g

In [13]:
dup_data.drop_duplicates(["Designation", "Department" , "Salary", "Age"], keep="last", inplace=True)


dup_data

    Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
1        2    1107     Officer          IT  30.0   80000.0
2        3    1203     Officer          HR  28.0       NaN
3        4    1005     Manager          HR  45.0  120000.0
5        6    2451  Accountant         NaN  34.0  100000.0
6        7    1111  Accountant    Accounts   NaN  110000.0
7        8    1001     Officer          IT  25.0   75000.0
8        9    1234     Manager          IT  23.0       NaN
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer         NaN  25.0       NaN
17      18    2123  Office Boy    Accounts  27.0   45000.0
25      20    6543     Officer  Production  29.0  100000.0
27      22    3214  Accountant     Account  49.0  123000.0
28      23    2156    Engineer  Production  45.0   89000.0
29      24    1098     Officer          IT  25.0  100000.0

In [14]:
dup_data.isna().sum()

Serial         0
Emp_ID         0
Designation    0
Department     2
Age            1
Salary         3
dtype: int64

In [19]:
dup_data.fillna(0, inplace=True)

In [20]:
dup_data.isna().sum()

Serial         0
Emp_ID         0
Designation    0
Department     0
Age            0
Salary         0
dtype: int64

In [21]:
dup_data

    Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
1        2    1107     Officer          IT  30.0   80000.0
2        3    1203     Officer          HR  28.0       0.0
3        4    1005     Manager          HR  45.0  120000.0
5        6    2451  Accountant           0  34.0  100000.0
6        7    1111  Accountant    Accounts   0.0  110000.0
7        8    1001     Officer          IT  25.0   75000.0
8        9    1234     Manager          IT  23.0       0.0
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer           0  25.0       0.0
17      18    2123  Office Boy    Accounts  27.0   45000.0
25      20    6543     Officer  Production  29.0  100000.0
27      22    3214  Accountant     Account  49.0  123000.0
28      23    2156    Engineer  Production  45.0   89000.0
29      24    1098     Officer          IT  25.0  100000.0