In [1]:
import pandas as pd

data = pd.read_csv("tested.csv")

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [8]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [24]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,None,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,None,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,None,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,None,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,None,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,None,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,None,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,None,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,None,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,None,1,1,2668,22.3583,NaN,C

In [25]:
data.Pclass.unique()

array([3, 2, 1])

In [27]:
dic = {1 : "Upper Class", 2 : "Middle Class", 3 : "Lower Class"}

In [29]:
data["Person Class"] = data.Pclass.map(dic)

data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Person Class
0,892,0,3,"Kelly, Mr. James",male,None,0,0,330911,7.8292,NaN,Q,Lower Class
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,None,1,0,363272,7.0000,NaN,S,Lower Class
2,894,0,2,"Myles, Mr. Thomas Francis",male,None,0,0,240276,9.6875,NaN,Q,Middle Class
3,895,0,3,"Wirz, Mr. Albert",male,None,0,0,315154,8.6625,NaN,S,Lower Class
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,None,1,1,3101298,12.2875,NaN,S,Lower Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,None,0,0,A.5. 3236,8.0500,NaN,S,Lower Class
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,None,0,0,PC 17758,108.9000,C105,C,Upper Class
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,None,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,Lower Class
416,1308,0,3,"Ware, Mr. Frederick",male,None,0,0,359309,8.0500,NaN,S,Lower Class
417,1309,0,3,"Peter, Master. Michael J",male,None,1,1,2668,22.3583,NaN,C,Lower Class